set(CPF_CONFIG "VS2019-shared-debug" CACHE STRING "the config name" FORCE)

include( "${CMAKE_CURRENT_LIST_DIR}/VS2019-shared.config.cmake" )

# GENERATOR AND TOOLCHAIN
set( CMAKE_CONFIGURATION_TYPES Debug CACHE STRING "" FORCE)

